{
 "title": "Loki 日志看板",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "命名空间", "query": "label_values(namespace)" },
   {
    "name": "label_app",
    "label": "应用（标签选择）",
    "query": "label_values({app=~\".+\"}, app)"
   },
   { "name": "container", "label": "容器", "query": "label_values(container)" },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)"
   },
   { "name": "interval", "label": "聚合时间", "query": "1d,1s,10s,1m,1h,12h,7d" },
   {
    "name": "pod_stream",
    "label": "日志流（Pod）",
    "query": "label_values({pod=\"$pod_name\"}, stream)"
   }
  ]
 },
 "panels": [
  {
   "title": "日志生成分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"})[$interval])) by (container)"
    }
   ]
  },
  {
   "title": "错误日志分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"}|~\"(error|ERROR)\"!~\"(info|INFO)\") [$interval])) by (container)"
    }
   ]
  },
  {
   "title": "日志数",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"})[$interval]))"
    }
   ]
  },
  {
   "title": "错误日志数",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"}|~\"(error|ERROR)\"!~\"(info|INFO)\") [$interval]))"
    }
   ]
  },
  {
   "title": "错误日志总占比",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"}|~\"(error|ERROR)\"!~\"(info|INFO)\")[$interval]))*100/sum(count_over_time(({container=~\"$container\"})[$interval]))"
    }
   ]
  },
  {
   "title": "日志生成速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\"$container\"} [$interval])) by(container)"
    }
   ]
  },
  {
   "title": "错误日志生成速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"}|~\"(error|ERROR)\"!~\"(info|INFO)\")[$interval])) by (container)"
    }
   ]
  },
  {
   "title": "错误类型概要",
   "type": "table",
   "description": "(粒度固定24h)仅对部份日志进行格式化处理，筛选出需关注的内容",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10,sum by(container,dingding)(count_over_time({container=\"guandata-server\"}|~\"(error|ERROR)\"!~\"(info|INFO)\"|=\"DingTalk\"|regexp \"(?P<dingding>DingTalk.*)\"|line_format \"{{.dingding}}\" [24h])))"
    },
    {
     "expr": "topk(10,sum by(container,clickhouse)(count_over_time({container=\"guandata-server\"}|~\"(error|ERROR)\"!~\"(info|INFO)\"|=\"clickhouse\"|regexp \"(?P<message>error.*)\"|label_format clickhouse=message|line_format \"{{.clickhouse}}\"  [24h])))"
    },
    {
     "expr": "topk(10,sum by(container,cassandra)(count_over_time({container=\"guandata-server\"}|~\"(error|ERROR)\"!~\"(info|INFO)\"|=\"Task CASSANDRA\"!=\"Exception happens in Task CASSANDRA with id\"|regexp \"(?P<message1>\\\\{.*\\\\})\"|line_format \"{{.message1}}\"|json|label_format cassandra=message|line_format \"{{.cassandra}}\"  [24h])))"
    }
   ]
  },
  {
   "title": "Pod日志预览",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{container=~\"$container\"}"
    }
   ]
  },
  {
   "title": "错误日志预览",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "{container=~\"$container\"}|~\"(error|ERROR)\"!~\"(info|INFO)\""
    }
   ]
  }
 ]
}