apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app: promtail
    name: promtail
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - promtail
    resources:
    - podsecuritypolicies
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app: promtail
    name: promtail
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: promtail
  subjects:
  - kind: ServiceAccount
    name: promtail
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
    labels:
      app: promtail
    name: promtail
  secrets:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: promtail
    name: promtail-clusterrole
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs:
    - get
    - watch
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app: promtail
    name: promtail-clusterrolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: promtail-clusterrole
  subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
