apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: loki
    release: loki
    variant: headless
  name: loki-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki
  sessionAffinity: None
  type: ClusterIP
